import Head from 'next/head'
import Container from '@mui/material/Container'

export default function Layout(props)
{
    return(
        <>
            <Head>
                <title>{props.title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Container>
                    {props.children}
                </Container>
            </main>
            <footer>
            </footer>
        </>
    )
}